# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/golfu/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/golfu/proprietary/libcamerapp.so:obj/lib/libcamerapp.so
 
# All the blobs necessary for passion
PRODUCT_COPY_FILES += \
    vendor/htc/golfu/proprietary/updatecmds:/system/etc/updatecmds \
    vendor/htc/golfu/proprietary/updatecmds/google_generic_update.txt:/system/etc/updatecmds/google_generic_update.txt \
    vendor/htc/golfu/proprietary/agps_rm:/system/etc/agps_rm \
    vendor/htc/golfu/proprietary/AudioFilter.csv:/system/etc/AudioFilter.csv \
    vendor/htc/golfu/proprietary/AudioFilter_HP.csv:/system/etc/AudioFilter_HP.csv \
    vendor/htc/golfu/proprietary/AudioPara4.csv:/system/etc/AudioPara4.csv \
    vendor/htc/golfu/proprietary/AudioPara4_WB.csv:/system/etc/AudioPara4_WB.csv \
    vendor/htc/golfu/proprietary/AudioPreProcess.csv:/system/etc/AudioPreProcess.csv \
    vendor/htc/golfu/proprietary/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/htc/golfu/proprietary/libGLES_android.so:/system/lib/egl/libGLES_android.so \
    vendor/htc/golfu/proprietary/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/golfu/proprietary/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/golfu/proprietary/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
    vendor/htc/golfu/proprietary/eglsubAndroid.so:/system/lib/egl/eglsubAndroid.so \
    vendor/htc/golfu/proprietary/libmm-adspsvc.so:/system/lib/libmm-adspsvc.so \
    vendor/htc/golfu/proprietary/libOmxH264Dec.so:/system/lib/libOmxH264Dec.so \
    vendor/htc/golfu/proprietary/libOmxMpeg4Dec.so:/system/lib/libOmxMpeg4Dec.so \
    vendor/htc/golfu/proprietary/libOmxVidEnc.so:/system/lib/libOmxVidEnc.so \
    vendor/htc/golfu/proprietary/libgsl.so:/system/lib/libgsl.so \
    vendor/htc/golfu/proprietary/libsc-a2xx.so:/system/lib/libsc-a2xx.so \
    vendor/htc/golfu/proprietary/libOpenVG.so:/system/lib/libOpenVG.so \
    vendor/htc/golfu/proprietary/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \
    vendor/htc/golfu/proprietary/libaudioeq.so:/system/lib/libaudioeq.so \
    vendor/htc/golfu/proprietary/libhtc_ril.so:/system/lib/libhtc_ril.so \
    vendor/htc/golfu/proprietary/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/htc/golfu/proprietary/libcamerapp.so:system/lib/libcamerapp.so \
    system/bluetooth/data/main.le.conf:system/etc/bluetooth/main.conf
